# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

common_env: &common_env
  MAVEN_OPTS: -Xmx1024m

job_default: &job_defaults
  docker:
    - image: circleci/openjdk:8-jdk-node-browsers

jobs:
  e2e-tests:
    <<: *job_defaults
    environment:
      <<: *common_env

    steps:
      - checkout
      - restore_cache:
          key: syndesis-e2e-qe-mvn-{{ checksum "pom.xml" }}
      - run:
          name: Execute tests
          command: |
            if [ -n "${OPENSHIFT_TOKEN}" ]; then
                curl -fsSL https://github.com/openshift/origin/releases/download/v3.6.0/openshift-origin-client-tools-v3.6.0-c4dd4cf-linux-64bit.tar.gz | sudo tar xz -C /usr/bin --strip-components 1
                oc login --server "${OPENSHIFT_SERVER}" --token "${OPENSHIFT_TOKEN}"

                oc get cm syndesis-qe-test-config -o jsonpath="{ .data.test_properties }" -n syndesis-ci > test.properties
                oc get cm syndesis-qe-credentials -o jsonpath="{ .data.credentials }" -n syndesis-ci > credentials.json
            else
              echo "Setup OpenShift cluster credentials"
            fi

            nohup /usr/bin/Xvfb :99 -ac -screen 0 1280x720x24 &
            export DISPLAY=:99
            ./mvnw clean test -P ui -Dcucumber.options="--tags ~@wip"
      - store_artifacts:
          path: ~/ui-tests/target/cucumber
      - store_test_results:
          path: ~/ui-tests/target/cucumber/cucumber-junit.xml
      - save_cache:
          key: syndesis-e2e-qe-mvn-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

  build:
    <<: *job_defaults
    environment:
      <<: *common_env

    steps:
      - checkout
      - restore_cache:
          key: syndesis-qe-mvn-{{ checksum "pom.xml" }}
      - run:
          name: Build tests
          command: |
            ./mvnw clean install -DskipTests
      - save_cache:
          key: syndesis-qe-mvn-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

workflows:
  version: 2
  syndesis-qe:
    jobs:
      - build
      - e2e-tests:
          requires:
            - build
          filters:
            branches:
              only: master
